/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteRouteImport } from './routes/_student/route'
import { Route as CoordinatorRouteRouteImport } from './routes/_coordinator/route'
import { Route as CompanyRouteRouteImport } from './routes/_company/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLogoutRouteImport } from './routes/(auth)/logout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as StudentProfileIndexRouteImport } from './routes/_student/profile/index'
import { Route as CoordinatorInternshipCoordinatorRegisterRouteImport } from './routes/_coordinator/internship-coordinator/register'
import { Route as CompanyCompanyProfileRouteImport } from './routes/_company/company/profile'

const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRouteRoute = CoordinatorRouteRouteImport.update({
  id: '/_coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRouteRoute = CompanyRouteRouteImport.update({
  id: '/_company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLogoutRoute = authLogoutRouteImport.update({
  id: '/(auth)/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileIndexRoute = StudentProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const CoordinatorInternshipCoordinatorRegisterRoute =
  CoordinatorInternshipCoordinatorRegisterRouteImport.update({
    id: '/internship-coordinator/register',
    path: '/internship-coordinator/register',
    getParentRoute: () => CoordinatorRouteRoute,
  } as any)
const CompanyCompanyProfileRoute = CompanyCompanyProfileRouteImport.update({
  id: '/company/profile',
  path: '/company/profile',
  getParentRoute: () => CompanyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/register': typeof authRegisterRoute
  '/company/profile': typeof CompanyCompanyProfileRoute
  '/internship-coordinator/register': typeof CoordinatorInternshipCoordinatorRegisterRoute
  '/profile/': typeof StudentProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/register': typeof authRegisterRoute
  '/company/profile': typeof CompanyCompanyProfileRoute
  '/internship-coordinator/register': typeof CoordinatorInternshipCoordinatorRegisterRoute
  '/profile': typeof StudentProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_company': typeof CompanyRouteRouteWithChildren
  '/_coordinator': typeof CoordinatorRouteRouteWithChildren
  '/_student': typeof StudentRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/logout': typeof authLogoutRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_company/company/profile': typeof CompanyCompanyProfileRoute
  '/_coordinator/internship-coordinator/register': typeof CoordinatorInternshipCoordinatorRegisterRoute
  '/_student/profile/': typeof StudentProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/company/profile'
    | '/internship-coordinator/register'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/company/profile'
    | '/internship-coordinator/register'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_company'
    | '/_coordinator'
    | '/_student'
    | '/(auth)/login'
    | '/(auth)/logout'
    | '/(auth)/register'
    | '/_company/company/profile'
    | '/_coordinator/internship-coordinator/register'
    | '/_student/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRouteRoute: typeof CompanyRouteRouteWithChildren
  CoordinatorRouteRoute: typeof CoordinatorRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authLogoutRoute: typeof authLogoutRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coordinator': {
      id: '/_coordinator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CoordinatorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_company': {
      id: '/_company'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CompanyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/logout': {
      id: '/(auth)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/profile/': {
      id: '/_student/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof StudentProfileIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_coordinator/internship-coordinator/register': {
      id: '/_coordinator/internship-coordinator/register'
      path: '/internship-coordinator/register'
      fullPath: '/internship-coordinator/register'
      preLoaderRoute: typeof CoordinatorInternshipCoordinatorRegisterRouteImport
      parentRoute: typeof CoordinatorRouteRoute
    }
    '/_company/company/profile': {
      id: '/_company/company/profile'
      path: '/company/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof CompanyCompanyProfileRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
  }
}

interface CompanyRouteRouteChildren {
  CompanyCompanyProfileRoute: typeof CompanyCompanyProfileRoute
}

const CompanyRouteRouteChildren: CompanyRouteRouteChildren = {
  CompanyCompanyProfileRoute: CompanyCompanyProfileRoute,
}

const CompanyRouteRouteWithChildren = CompanyRouteRoute._addFileChildren(
  CompanyRouteRouteChildren,
)

interface CoordinatorRouteRouteChildren {
  CoordinatorInternshipCoordinatorRegisterRoute: typeof CoordinatorInternshipCoordinatorRegisterRoute
}

const CoordinatorRouteRouteChildren: CoordinatorRouteRouteChildren = {
  CoordinatorInternshipCoordinatorRegisterRoute:
    CoordinatorInternshipCoordinatorRegisterRoute,
}

const CoordinatorRouteRouteWithChildren =
  CoordinatorRouteRoute._addFileChildren(CoordinatorRouteRouteChildren)

interface StudentRouteRouteChildren {
  StudentProfileIndexRoute: typeof StudentProfileIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentProfileIndexRoute: StudentProfileIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRouteRoute: CompanyRouteRouteWithChildren,
  CoordinatorRouteRoute: CoordinatorRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authLogoutRoute: authLogoutRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
